version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - VITE_NEWSDATA_API_KEY=pub_057b1f4feec14f1aa5f6634c54e68f96
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
